language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
install:
  - pip install poetry
  - cd shuecm
  - poetry install
  - cd ..
script:
  - echo "all works!"