site_name: ShueCM
nav:
  - Get started: index.md
  - Upgrade: upgrade.md
  - Performance: performance.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'shueteam/shuecm'
repo_url: 'https://github.com/shueteam/shuecm'
