site_name: ShueCM
nav:
  - Get started: index.md
  - Upgrade: upgrade.md
  - Performance: performance.md
  - Roles: roles.md
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: 'shueteam/shuecm'
repo_url: 'https://github.com/shueteam/shuecm'
